language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  - NODE_VERSION="10"
before_install:
  - nvm install $NODE_VERSION
  - . heroku.sh
  - ls lib
before_script:
  - cd front/videoroom
script:
  - npm install --save
  - npm run build
  - cd ../..
  - cp -r -T front/videoroom/build src/main/resources/public
  - mv src/main/resources/public/index.html src/main/resources/templates
  - mvn clean test
  - git add --all
  - git add -f lib
  - git commit --allow-empty -m "remote heroku deploy"

deploy:
  provider: heroku
  api_key:
    secure: M8Mwf0wm5bgSOBid8zMSz2d4rZuHSz5p8y/NkkrPDdgQcUNj9WhXa8eXglsh+pLphpviVeyngrdAPMQgoJNygs4/8zaU8Z7NsX6RgI386i1EpVV9e0vNVPVyu6wDgURt9CZS6kxS9+MQck4+LcJyRiF8YeS8JNovTvRsYIDroJT+k3Z+EgJi5ff71jP3jphz/QANPz9jd/o9hOLD40lfIWUW0zAZpT6jz02EODyRf9USm/stP1sLUOysUyT/iQ+oDHShUUlJw8lMzvL60W9HdAohpalFvJNa+rf/B6GO4l52M+UFkfNwWB+6vWEmSnHcNjW2Dml2WeOk+gDjlesFihTs3M0KPPa5LdvBIgpX7FBz9d0VHt7ao1Cy2rpm4AhrLM2X4Ux00/R5Gorxec/mH3L3VlSaXZP47UdoEYGTsn62Q5HzYBfeVyyzEvcRTRJKPLG5OLQvd3MDMgxULxP6PNPQN5Deme8GjYhk/PgYQtyZ7Mjq9uKuA4sjDQWDyZa9YpP2/CD87IOjDWteY8AtGjriTJOv2uRpzn9flvN6UkfA0uOkZrfPDraLUsLfqzKOHzBdQFrOIw4C99gmhDKXSEXqjDbDL/SFqd81KTVE3n9zm3LbXbpCfuMyh2HcnoTyp/vsvDCHr4LfHjk6SlJRGLqFC7LZAVUdVWJzSdEAW9Y=
  app: videohtroom
  on:
    repo: JS-Ng/teleRoom